#!/bin/sh
./configure CFLAGS="-g -O0" --with-engine=intrp --with-staticvm --with-staticbin --enable-vmdebug --with-trishul-keystore=trishul.keystore --with-trishul-keystore-alias=trishul --with-trishul-keystore-password=trishul 
